### ISSUE TITLE
cannot perform a search in a guild

### ISSUE THREAD

**Issue by searinminecraft** [aiko-chan-ai/DiscordBotClient#106]
when trying to search, i get a "We dropped the magnifying class" error, and an error appears in the console:

```
GET /bot/api/v9/guilds/376120568908611594/messages/search?author_id=1064038532403961937 500 3.694 ms - 1375
ReferenceError: text is not defined
    at /tmp/.mount_DiscorQyLlFx/resources/app/AppCore/routes/guilds/#id/messages/search.js:10:18
    at newFn (/tmp/.mount_DiscorQyLlFx/resources/app/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/tmp/.mount_DiscorQyLlFx/resources/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/tmp/.mount_DiscorQyLlFx/resources/app/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/tmp/.mount_DiscorQyLlFx/resources/app/node_modules/express/lib/router/route.js:114:3)
    at newFn (/tmp/.mount_DiscorQyLlFx/resources/app/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/tmp/.mount_DiscorQyLlFx/resources/app/node_modules/express/lib/router/layer.js:95:5)
    at /tmp/.mount_DiscorQyLlFx/resources/app/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/tmp/.mount_DiscorQyLlFx/resources/app/node_modules/express/lib/router/index.js:346:12)
    at next (/tmp/.mount_DiscorQyLlFx/resources/app/node_modules/express/lib/router/index.js:280:10)
```

![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/114207889/6e820d53-87e0-4afd-b251-853348500329)

**Comment by aiko-chan-ai** [comment]
bot user can't use this api, I'll fix it later because it's not important

**Comment by searinminecraft** [comment]
> bot user can't use this api, I'll fix it later because it's not important

ah okay, thanks for the info

**Comment by aiko-chan-ai** [comment]
maybe I'll try implementing it later

**Comment by aiko-chan-ai** [comment]
but it can only find messages by date

**Comment by Llamuck** [comment]
yes please!

**Comment by worldInColors** [comment]
> maybe I'll try implementing it later

did you implement it yet?
