### ISSUE TITLE
Client crashing on startup.

### ISSUE THREAD

**Issue by flleeppyy** [aiko-chan-ai/DiscordBotClient#204]
On 3.5.0

```

Vencord   NoTrack  Failed to disable Sentry. Falling back to deleting window.DiscordSentry

sentry.4aa65d8….js:14 TypeError: d(...)(...).shiftRight is not a function
    at b (web.35a4267….js:12:10174683)
    at Object.M [as getUserAvatarURL] (web.35a4267….js:12:10175392)
    at h.getAvatarURL (web.35a4267….js:12:9503534)
    at E (web.35a4267….js:12:8454271)
    at web.35a4267….js:12:9129560
    at Object.useMemo (web.35a4267….js:12:1328978)
    at t.useMemo (web.35a4267….js:12:1440925)
    at d (web.35a4267….js:12:9129532)
    at l (web.35a4267….js:12:9130085)
    at K (5f1a0b8….js:1:4194)
    at aY (web.35a4267….js:12:1322668)
    at l (web.35a4267….js:12:1379315)
    at lu (web.35a4267….js:12:1370772)
    at ls (web.35a4267….js:12:1370700)
    at lo (web.35a4267….js:12:1370563)
    at s4 (web.35a4267….js:12:1366933)
    at s3 (web.35a4267….js:12:1365900)
    at v (web.35a4267….js:12:1555532)
    at b (web.35a4267….js:12:1556062)
    at T.C.<computed> (web.35a4267….js:1:1271621)
    at L (web.35a4267….js:1:1271386)
    at MessagePort.D (web.35a4267….js:1:1271445)
sentry.4aa65d8….js:14 TypeError: d(...)(...).shiftRight is not a function
    at b (web.35a4267….js:12:10174683)
    at Object.M [as getUserAvatarURL] (web.35a4267….js:12:10175392)
    at h.getAvatarURL (web.35a4267….js:12:9503534)
    at E (web.35a4267….js:12:8454271)
    at web.35a4267….js:12:9129560
    at Object.useMemo (web.35a4267….js:12:1328978)
    at t.useMemo (web.35a4267….js:12:1440925)
    at d (web.35a4267….js:12:9129532)
    at l (web.35a4267….js:12:9130085)
    at K (5f1a0b8….js:1:4194)
    at aY (web.35a4267….js:12:1322668)
    at l (web.35a4267….js:12:1379315)
    at lu (web.35a4267….js:12:1370772)
    at ls (web.35a4267….js:12:1370700)
    at lo (web.35a4267….js:12:1370563)
    at s4 (web.35a4267….js:12:1366933)
    at s8 (web.35a4267….js:12:1367739)
    at iT (web.35a4267….js:12:1306525)
    at l_ (web.35a4267….js:12:1372300)
    at ld (web.35a4267….js:12:1371265)
    at s3 (web.35a4267….js:12:1366210)
    at v (web.35a4267….js:12:1555532)
    at b (web.35a4267….js:12:1556062)
    at T.C.<computed> (web.35a4267….js:1:1271621)
    at L (web.35a4267….js:1:1271386)
    at MessagePort.D (web.35a4267….js:1:1271445)
```

**Comment by aiko-chan-ai** [comment]
fixed
