### ISSUE TITLE
Loading

### ISSUE THREAD

**Issue by xYanzu** [aiko-chan-ai/DiscordBotClient#86]
When I launch the app, infinite loading appears
![image_2024-01-17_184031278](https://github.com/aiko-chan-ai/DiscordBotClient/assets/111741209/34b70b7e-2802-4592-9892-9051b2a8cc18)

[2024-01-04 20:45:13.919] [info]  App starting...
[2024-01-04 20:45:14.034] [info]  Checking for updates...
[2024-01-04 20:45:14.146] [info]  Electron UserData: C:\Users\pubto\AppData\Roaming\Discord Bot Client
[2024-01-04 20:45:14.854] [info]  Server is running on port 2023
[2024-01-04 20:45:14.894] [info]  Vencord-Web Extension loaded, version: 1.2.8
[2024-01-04 20:45:15.141] [info]  Load script target /assets/9a287279797be8995feb.js
[2024-01-04 20:48:54.143] [info]  App closing...
[2024-01-04 20:49:17.885] [info]  App starting...
[2024-01-04 20:49:17.914] [info]  Checking for updates...
[2024-01-04 20:49:17.959] [info]  Electron UserData: C:\Users\pubto\AppData\Roaming\Discord Bot Client
[2024-01-04 20:49:18.360] [info]  Server is running on port 2023
[2024-01-04 20:49:18.380] [info]  Vencord-Web Extension loaded, version: 1.2.8
[2024-01-04 20:49:18.709] [info]  Load script target /assets/9a287279797be8995feb.js
[2024-01-17 01:04:25.943] [info]  App starting...
[2024-01-17 01:04:26.038] [info]  Checking for updates...
[2024-01-17 01:04:26.140] [info]  Electron UserData: C:\Users\pubto\AppData\Roaming\Discord Bot Client
[2024-01-17 01:04:26.877] [info]  Server is running on port 2023
[2024-01-17 01:04:26.911] [info]  Vencord-Web Extension loaded, version: 1.2.8
[2024-01-17 01:04:27.106] [info]  Load script target /assets/9a287279797be8995feb.js
[2024-01-17 01:05:48.560] [info]  App starting...
[2024-01-17 01:05:48.588] [info]  Checking for updates...
[2024-01-17 01:05:48.632] [info]  Electron UserData: C:\Users\pubto\AppData\Roaming\Discord Bot Client
[2024-01-17 01:05:49.001] [info]  Server is running on port 2023
[2024-01-17 01:05:49.001] [info]  Server is running on port 2024
[2024-01-17 01:05:49.021] [info]  Vencord-Web Extension loaded, version: 1.2.8
[2024-01-17 01:05:49.134] [info]  Load script target /assets/9a287279797be8995feb.js
[2024-01-17 01:10:07.028] [info]  App starting...
[2024-01-17 01:10:07.054] [info]  Checking for updates...
[2024-01-17 01:10:07.098] [info]  Electron UserData: C:\Users\pubto\AppData\Roaming\Discord Bot Client
[2024-01-17 01:10:07.804] [info]  Server is running on port 2023
[2024-01-17 01:10:07.804] [info]  Server is running on port 2024
[2024-01-17 01:10:07.805] [info]  Server is running on port 2025
[2024-01-17 01:10:07.825] [info]  Vencord-Web Extension loaded, version: 1.2.8
[2024-01-17 01:10:07.940] [info]  Load script target /assets/9a287279797be8995feb.js
[2024-01-17 16:54:18.336] [info]  App starting...
[2024-01-17 16:54:18.419] [info]  Checking for updates...
[2024-01-17 16:54:18.503] [info]  Electron UserData: C:\Users\pubto\AppData\Roaming\Discord Bot Client
[2024-01-17 16:54:19.196] [info]  Server is running on port 2023
[2024-01-17 16:54:19.228] [info]  Vencord-Web Extension loaded, version: 1.2.8
[2024-01-17 16:54:19.513] [info]  Load script target /assets/9a287279797be8995feb.js
[2024-01-17 16:54:32.372] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 16:55:28.049] [info]  App starting...
[2024-01-17 16:55:28.075] [info]  Checking for updates...
[2024-01-17 16:55:28.122] [info]  Electron UserData: C:\Users\pubto\AppData\Roaming\Discord Bot Client
[2024-01-17 16:55:28.543] [info]  Server is running on port 2023
[2024-01-17 16:55:28.544] [info]  Server is running on port 2024
[2024-01-17 16:55:28.566] [info]  Vencord-Web Extension loaded, version: 1.2.8
[2024-01-17 16:55:28.679] [info]  Load script target /assets/9a287279797be8995feb.js
[2024-01-17 16:56:04.038] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 16:58:08.162] [info]  App closing...
[2024-01-17 16:58:08.162] [info]  App closing...
[2024-01-17 16:58:28.230] [info]  App starting...
[2024-01-17 16:58:28.274] [info]  Checking for updates...
[2024-01-17 16:58:28.325] [info]  Electron UserData: C:\Users\pubto\AppData\Roaming\Discord Bot Client
[2024-01-17 16:58:28.746] [info]  Server is running on port 2023
[2024-01-17 16:58:28.772] [info]  Vencord-Web Extension loaded, version: 1.2.8
[2024-01-17 16:58:28.904] [info]  Load script target /assets/9a287279797be8995feb.js
[2024-01-17 16:58:32.068] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 16:59:14.497] [info]  Checking for updates...
[2024-01-17 16:59:18.805] [info]  App closing...
[2024-01-17 16:59:31.883] [info]  App starting...
[2024-01-17 16:59:31.911] [info]  Checking for updates...
[2024-01-17 16:59:31.959] [info]  Electron UserData: C:\Users\pubto\AppData\Roaming\Discord Bot Client
[2024-01-17 16:59:32.638] [info]  Server is running on port 2023
[2024-01-17 16:59:32.659] [info]  Vencord-Web Extension loaded, version: 1.2.8
[2024-01-17 16:59:32.787] [info]  Load script target /assets/9a287279797be8995feb.js
[2024-01-17 16:59:36.114] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 16:59:48.933] [info]  Load script target /assets/9a287279797be8995feb.js
[2024-01-17 16:59:52.052] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 17:02:12.591] [info]  App closing...
[2024-01-17 17:02:29.965] [info]  App starting...
[2024-01-17 17:02:29.993] [info]  Checking for updates...
[2024-01-17 17:02:30.041] [info]  Electron UserData: C:\Users\pubto\AppData\Roaming\Discord Bot Client
[2024-01-17 17:02:30.418] [info]  Server is running on port 2023
[2024-01-17 17:02:30.438] [info]  Vencord-Web Extension loaded, version: 1.2.8
[2024-01-17 17:02:30.562] [info]  Load script target /assets/9a287279797be8995feb.js
[2024-01-17 17:02:34.066] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 17:07:57.240] [info]  App closing...
[2024-01-17 17:08:18.393] [info]  App starting...
[2024-01-17 17:08:18.437] [info]  Checking for updates...
[2024-01-17 17:08:18.489] [info]  Electron UserData: C:\Users\pubto\AppData\Roaming\Discord Bot Client
[2024-01-17 17:08:19.164] [info]  Server is running on port 2023
[2024-01-17 17:08:19.196] [info]  Vencord-Web Extension loaded, version: 1.2.8
[2024-01-17 17:08:19.339] [info]  Load script target /assets/9a287279797be8995feb.js
[2024-01-17 17:08:23.000] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 17:12:50.018] [info]  App closing...
[2024-01-17 17:13:19.765] [info]  App starting...
[2024-01-17 17:13:19.810] [info]  Checking for updates...
[2024-01-17 17:13:19.864] [info]  Electron UserData: C:\Users\pubto\AppData\Roaming\Discord Bot Client
[2024-01-17 17:13:20.593] [info]  Server is running on port 2023
[2024-01-17 17:13:20.622] [info]  Vencord-Web Extension loaded, version: 1.2.8
[2024-01-17 17:13:20.752] [info]  Load script target /assets/9a287279797be8995feb.js
[2024-01-17 17:13:24.033] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 17:16:33.279] [info]  App closing...
[2024-01-17 17:16:58.441] [info]  App starting...
[2024-01-17 17:16:58.487] [info]  Checking for updates...
[2024-01-17 17:16:58.536] [info]  Electron UserData: C:\Users\pubto\AppData\Roaming\Discord Bot Client
[2024-01-17 17:16:58.908] [info]  Server is running on port 2023
[2024-01-17 17:16:58.946] [info]  Vencord-Web Extension loaded, version: 1.2.8
[2024-01-17 17:16:59.179] [info]  Load script target /assets/9a287279797be8995feb.js
[2024-01-17 17:17:03.357] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 17:27:10.831] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 17:30:34.842] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 17:33:45.821] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 17:37:45.883] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 17:42:18.811] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 17:46:47.846] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 17:51:44.883] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 17:55:48.872] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 18:00:27.841] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 18:04:38.967] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 18:09:19.906] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 18:12:57.606] [info]  App starting...
[2024-01-17 18:12:57.646] [info]  Checking for updates...
[2024-01-17 18:12:57.696] [info]  Electron UserData: C:\Users\pubto\AppData\Roaming\Discord Bot Client
[2024-01-17 18:12:58.372] [info]  Server is running on port 2023
[2024-01-17 18:12:58.373] [info]  Server is running on port 2024
[2024-01-17 18:12:58.397] [info]  Vencord-Web Extension loaded, version: 1.2.8
[2024-01-17 18:12:58.533] [info]  Load script target /assets/9a287279797be8995feb.js
[2024-01-17 18:13:29.915] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\Downloads\DiscordBotClient-electron\DiscordBotClient-electron\dist\win-unpacked\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 18:14:20.470] [info]  App closing...
[2024-01-17 18:14:21.948] [info]  App closing...
[2024-01-17 18:14:26.436] [info]  App starting...
[2024-01-17 18:14:26.464] [info]  Checking for updates...
[2024-01-17 18:14:26.510] [info]  Electron UserData: C:\Users\pubto\AppData\Roaming\Discord Bot Client
[2024-01-17 18:14:26.900] [info]  Server is running on port 2023
[2024-01-17 18:14:26.918] [info]  Vencord-Web Extension loaded, version: 1.2.8
[2024-01-17 18:14:27.042] [info]  Load script target /assets/9a287279797be8995feb.js
[2024-01-17 18:14:33.362] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\Downloads\DiscordBotClient-electron\DiscordBotClient-electron\dist\win-unpacked\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 18:17:04.063] [info]  App starting...
[2024-01-17 18:17:04.109] [info]  Checking for updates...
[2024-01-17 18:17:04.160] [info]  Electron UserData: C:\Users\pubto\AppData\Roaming\Discord Bot Client
[2024-01-17 18:17:04.606] [info]  Server is running on port 2023
[2024-01-17 18:17:04.637] [info]  Vencord-Web Extension loaded, version: 1.2.8
[2024-01-17 18:17:04.901] [info]  Load script target /assets/9a287279797be8995feb.js
[2024-01-17 18:17:08.925] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 18:20:35.742] [info]  App closing...
[2024-01-17 18:21:55.967] [info]  App starting...
[2024-01-17 18:21:56.011] [info]  Checking for updates...
[2024-01-17 18:21:56.055] [info]  Electron UserData: C:\Users\pubto\AppData\Roaming\Discord Bot Client
[2024-01-17 18:21:56.786] [info]  Server is running on port 2023
[2024-01-17 18:21:56.817] [info]  Vencord-Web Extension loaded, version: 1.2.8
[2024-01-17 18:21:58.698] [info]  Load script target /assets/9a287279797be8995feb.js
[2024-01-17 18:22:02.066] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 18:28:23.833] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 18:30:45.849] [info]  Load script target /assets/9a287279797be8995feb.js
[2024-01-17 18:30:49.080] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 18:31:03.642] [info]  Load script target /assets/9a287279797be8995feb.js
[2024-01-17 18:31:06.611] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 18:31:16.099] [info]  App closing...
[2024-01-17 18:34:05.647] [info]  App starting...
[2024-01-17 18:34:05.692] [info]  Checking for updates...
[2024-01-17 18:34:05.740] [info]  Electron UserData: C:\Users\pubto\AppData\Roaming\Discord Bot Client
[2024-01-17 18:34:06.432] [info]  Server is running on port 2023
[2024-01-17 18:34:06.464] [info]  Vencord-Web Extension loaded, version: 1.2.8
[2024-01-17 18:34:06.599] [info]  Load script target /assets/9a287279797be8995feb.js
[2024-01-17 18:34:10.129] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
[2024-01-17 18:34:16.985] [info]  Checking for updates...
[2024-01-17 18:34:29.147] [info]  App closing...
[2024-01-17 18:35:33.244] [info]  App starting...
[2024-01-17 18:35:33.288] [info]  Checking for updates...
[2024-01-17 18:35:33.343] [info]  Electron UserData: C:\Users\pubto\AppData\Roaming\Discord Bot Client
[2024-01-17 18:35:33.729] [info]  Server is running on port 2023
[2024-01-17 18:35:33.764] [info]  Vencord-Web Extension loaded, version: 1.2.8
[2024-01-17 18:35:34.021] [info]  Load script target /assets/9a287279797be8995feb.js
[2024-01-17 18:37:26.092] [info]  App closing...
[2024-01-17 18:37:47.290] [info]  App starting...
[2024-01-17 18:37:47.337] [info]  Checking for updates...
[2024-01-17 18:37:47.392] [info]  Electron UserData: C:\Users\pubto\AppData\Roaming\Discord Bot Client
[2024-01-17 18:37:49.287] [info]  Server is running on port 2023
[2024-01-17 18:37:49.319] [info]  Vencord-Web Extension loaded, version: 1.2.8
[2024-01-17 18:37:49.452] [info]  Load script target /assets/9a287279797be8995feb.js
[2024-01-17 18:37:54.050] [error] Error: MESSAGE_CONTENT is required
    at IpcMainImpl.<anonymous> (C:\Users\pubto\AppData\Local\Programs\discord-bot-client\resources\app\AppCore\index.js:329:10)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)

**Comment by VillainsRule** [comment]
The bot in question does not have the needed intents. In the bot's dashboard, go to Bot and enable the Message Content intent.
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/101288516/60b5cd7c-9e59-461f-8be7-ccd6e743e232)

**Comment by xYanzu** [comment]
How do I reset, because as soon as I start loading it will appear

**Comment by VillainsRule** [comment]
What device are you on?

**Comment by xYanzu** [comment]
on windows 11

**Comment by VillainsRule** [comment]
I have no idea. If you can open DevTools, you can attempt to change the token from localStorage.

**Comment by xYanzu** [comment]
possible to show me an ss where it is located pls ?

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/3f0bc98d-71a2-4d27-995c-a51d74928502)
