### ISSUE TITLE
After instalation

### ISSUE THREAD

**Issue by MewiPowi** [aiko-chan-ai/DiscordBotClient#98]
![obraz_2024-02-04_110006521](https://github.com/aiko-chan-ai/DiscordBotClient/assets/124863759/d20c90ed-8f85-4483-9e5d-e2430d9a8142)

**Comment by searinminecraft** [comment]
having the same issue here on Linux appimage

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '../VencordExtension/manifest.json'
Require stack:
- /tmp/.mount_DiscorzPPWOB/resources/app/AppCore/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1084:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:114728)
    at Module._load (node:internal/modules/cjs/loader:929:27)
    at l._load (node:electron/js2c/asar_bundle:2:13642)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/tmp/.mount_DiscorzPPWOB/resources/app/AppCore/index.js:20:5)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
```

(you should probably change the title to "Does not launch due to missing module")

**Comment by aiko-chan-ai** [comment]
Are you using version 3.0.0?
I deleted that version because there were too many errors ;-;

**Comment by aiko-chan-ai** [comment]
mb

**Comment by aiko-chan-ai** [comment]
i forgot VencordExtension folder

**Comment by aiko-chan-ai** [comment]
try latest

**Comment by searinminecraft** [comment]
> try latest

nope

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module './OtherRoute'
Require stack:
- /tmp/.mount_DiscorfDxI4X/resources/app/AppCore/server.js
- /tmp/.mount_DiscorfDxI4X/resources/app/AppCore/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1084:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:114728)
    at Module._load (node:internal/modules/cjs/loader:929:27)
    at l._load (node:electron/js2c/asar_bundle:2:13642)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/tmp/.mount_DiscorfDxI4X/resources/app/AppCore/server.js:5:20)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
```

**Comment by aiko-chan-ai** [comment]
try again (v3.1.0)

**Comment by searinminecraft** [comment]
> try again (v3.1.0)

the issue is now fixed. thanks (sorry for late reply)
